%Particle Cost Update
function [ particle ] = ParticleCostUpdate( pop_size, particle)
    for i=1:pop_size
        %Update Particle Cost
        particle(i).Cost = fitness([particle(i).Position1,...
                                    particle(i).Position2,...
                                    particle(i).Position3,...
                                    particle(i).Position4,...
                                    particle(i).Position5,...
                                    particle(i).Position6,...
                                    particle(i).Position7,...
                                    particle(i).Position8,...
                                    particle(i).Position9,...
                                    particle(i).Position10]);
    end
end